name: Notunterkunft-Plugin
main: NotunterkunftPlugin
api-version: 1.17
version: 1.0
commands:
    notunterkunft:
        description: Baut eine Notunterkunft fuer die Nacht
        usage: /notunterkunft
        aliases: [not]