name: Kugel-Plugin
main: KugelPlugin
api-version: 1.17
version: 1.0
commands:
    kugel:
        description: Platziert eine Kugel mit dem angegebenen Radius ueber dem Spieler
        usage: /kugel <radius>
